
version: "3.3" 

services:
  ansible:
    build:
      context: ./dockerfiles/ansible/
      dockerfile: Dockerfile
    container_name: ansible_container
    hostname: ansible_host
    ports:
      - 8080:8080
    volumes:
      - ./configuration/:/ansible/configuration
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - ./hosts:/etc/ansible/hosts
      - ./webapp:/webapp
    networks: 
      internal:

  test1:
    build:
      context: ./dockerfiles/standardhost/
      dockerfile: Dockerfile
    container_name: host_4_webapp
    hostname: host_4_webapp
    ports:
      - 8000:8000
    networks:
      internal:
    

networks: 
  internal: