---

# Software provisioning 
- name : install pip3 
  apt:
    name: python3-pip
    state: latest

# Software provisioning 
- name: install flask
  pip: 
    name: flask 
    state: latest

# Software deployment
- name: copy a sample file 
  copy: 
    src: /webapp/main.py
    dest: /webapp/
    mode: 777

# server configuration management
- name: copy a flask service  file 
  copy: 
    src: /webapp/myflask.service
    dest: /lib/systemd/system/

# server configuration management
- name: copy a flask service  file 
  copy: 
    src: /webapp/myflask.conf
    dest: /etc/init/


- name: start the server on port 8000
  service:
    name: myflask
    enabled: yes
    state: started

- name: start the server on port 8000
  systemd:
    state: started
    name: myflask
    
