---
- hosts: all
  become: yes 
    
  tasks:
  # Assignment 1 - Find the task at: /roles/installpip3/tasks/main.yml
    - name: install pip3 using apt package manager module 
      import_role:
        name: installpip3
      tags: installpip3 

  # Assignment 2 - Find the task at: /roles/installflask/tasks/main.yml
    - name: install flask using pip module
      import_role:
        name: installflask
      tags: installflask 

  # Assignment 3 - Find the task at: /roles/installwebapp/tasks/main.yml
    - name: deploy helloworld app using copy module 
      import_role:
        name: installwebapp
      tags: installwebapp 
  
  # Assignment 4 - Find the task at: /roles/runflask/tasks/main.yml
    - name: run flask using shell module 
      import_role:
        name: runflask
      tags: runflask 